const INIT_EXAMINATIONS = [
  {
    id: 0,
    sample_id: 0,
    sample_in_lab_id: 0,
    name: "MCV",
    result: 77.6,
    situation: "D",
    unit: "fL",
    starting_normal_range: 80,
    ending_normal_range: 95,
    date: "01/01/2022",
    isFavorite: true,
  },
  {
    id: 7,
    sample_id: 4,
    sample_in_lab_id: 7,
    name: "MCV",
    result: 80,
    situation: "",
    unit: "fL",
    starting_normal_range: 80,
    ending_normal_range: 95,
    date: "07/20/2022",
    isFavorite: true,
  },
  {
    id: 8,
    sample_id: 2,
    sample_in_lab_id: 2,
    name: "MCV",
    result: 90,
    situation: "",
    unit: "fL",
    starting_normal_range: 80,
    ending_normal_range: 95,
    date: "07/20/2022",
    isFavorite: true,
  },
  {
    id: 1,
    sample_id: 0,
    sample_in_lab_id: 0,
    name: "MCH",
    result: 25.1,
    situation: "",
    unit: "pg",
    starting_normal_range: 25,
    ending_normal_range: 34,
    date: "01/01/2022",
    isFavorite: true,
  },
  {
    id: 2,
    sample_id: 0,
    sample_in_lab_id: 0,
    name: "MCHC",
    result: 32.3,
    situation: "",
    unit: "g/dL",
    starting_normal_range: 31.0,
    ending_normal_range: 37.0,
    date: "01/01/2022",
    isFavorite: false,
  },
  {
    id: 3,
    sample_id: 0,
    sample_in_lab_id: 0,
    name: "WBC",
    result: 10.05,
    situation: "Y",
    unit: "10^3/uL",
    starting_normal_range: 3.8,
    ending_normal_range: 10,
    date: "01/01/2022",
    isFavorite: false,
  },
  {
    id: 4,
    sample_id: 0,
    sample_in_lab_id: 0,
    name: "RDW",
    result: 15.4,
    situation: "Y",
    unit: "%",
    starting_normal_range: 11.2,
    ending_normal_range: 15,
    date: "01/01/2022",
    isFavorite: false,
  },
  {
    id: 5,
    sample_id: 0,
    sample_in_lab_id: 0,
    name: "RBC",
    result: 5.52,
    situation: "",
    unit: "10(6)/",
    starting_normal_range: 4,
    ending_normal_range: 6.2,
    date: "01/01/2022",
    isFavorite: false,
  },
  {
    id: 6,
    sample_id: 0,
    sample_in_lab_id: 0,
    name: "PLT",
    result: 399,
    situation: "",
    unit: "10^3/uL",
    starting_normal_range: 100,
    ending_normal_range: 400,
    date: "01/01/2022",
    isFavorite: true,
  },
  {
    id: 9,
    sample_id: 1,
    sample_in_lab_id: 3,
    name: "Ferritin",
    result: 81.8,
    situation: "",
    unit: "ug/L",
    starting_normal_range: 13,
    ending_normal_range: 150,
    date: "01/01/2022",
    isFavorite: true,
  },
];

export default INIT_EXAMINATIONS;
