const INIT_PATIENTS = [
  {
    id: 0,
    tc: null,
    name: "Sama",
    surname: "Jabri",
    gender: "F",
    email: "sama.jabri@outlook.com",
    username: "Sama",
    password: "Sama",
    age: null,
    weight: null,
    height: null,
    img_src: "",
  },
  {
    id: 1,
    tc: null,
    name: "Ahmad",
    surname: "Koz",
    gender: "M",
    email: "ahmad.koz@outlook.com",
    username: "Ahmad",
    password: "Ahmad",
    age: 26,
    weight: null,
    height: null,
    img_src: "",
  },
  {
    id: 2,
    tc: null,
    name: "Micheal",
    surname: "Jan",
    gender: "M",
    email: "micheal.jan@outlook.com",
    username: "Micheal",
    password: "Micheal",
    age: 66,
    weight: null,
    height: null,
    img_src: "",
  },
  {
    id: 3,
    tc: null,
    name: "Jessica",
    surname: "Day",
    gender: "F",
    email: "jessica.day@outlook.com",
    username: "Jessica",
    password: "Jessica",
    age: 40,
    weight: 65,
    height: 165,
    img_src: "",
  },
  {
    id: 4,
    tc: null,
    name: "Nataly",
    surname: "Nat",
    gender: "F",
    email: "nataly.nat@gmail.com",
    username: "Nataly",
    password: "Nataly",
    age: 87,
    weight: 65,
    height: 160,
    img_src: "",
  },
];

export default INIT_PATIENTS;
